In [2]:
import pandas as pd

In [3]:
cars = pd.read_csv('cars.csv')

PART A

In [11]:
print("Shape of cars:", cars.shape)
print("Column names:", cars.columns.tolist())

Shape of cars: (32, 12)
Column names: ['Model', 'mpg', 'cyl', 'disp', 'hp', 'drat', 'wt', 'qsec', 'vs', 'am', 'gear', 'carb']

In [5]:
cars_6_to_10 = cars.iloc[5:10]

In [14]:
cars_6_to_10_subset = cars_6_to_10.loc[:, ['Model', 'mpg', 'cyl', 'hp', 'gear']]
cars_6_to_10_subset

        Model   mpg  cyl   hp  gear
5     Valiant  18.1    6  105     3
6  Duster 360  14.3    8  245     3
7   Merc 240D  24.4    4   62     4
8    Merc 230  22.8    4   95     4
9    Merc 280  19.2    6  123     4

PART B

In [16]:
toyota = cars[cars['Model'] == 'Toyota Corolla']
display(toyota)

             Model   mpg  cyl  disp  hp  drat     wt  qsec  vs  am  gear  carb
19  Toyota Corolla  33.9    4  71.1  65  4.22  1.835  19.9   1   1     4     1

In [17]:
pontiac = cars.loc[cars['Model'] == 'Pontiac Firebird', ['Model', 'mpg', 'hp', 'wt']]
display(pontiac)

               Model   mpg   hp     wt
24  Pontiac Firebird  19.2  175  3.845

PART C

In [18]:
selected_cars = cars.loc[cars['Model'].isin(target_models), ['Model', 'mpg', 'cyl', 'hp', 'gear']]
target_models = ['Datsun 710', 'Lotus Europa', 'Ferrari Dino']

In [19]:
display(selected_cars)
print("Shape of selected_cars:", selected_cars.shape)

           Model   mpg  cyl   hp  gear
2     Datsun 710  22.8    4   93     4
27  Lotus Europa  30.4    4  113     5
29  Ferrari Dino  19.7    6  175     5

Shape of selected_cars: (3, 5)